name: Manage outdate dependencies and create issue

on: 
  # schedule:
  #   - cron: '0 0 * * 1'
  workflow_dispatch:
  push:

jobs:
  check-outdated-dependencies:
    runs-on: macos-latest
    name: Check outdate dependencies and create issue if it doesn't exist
    steps:
      - uses: actions/checkout@v3

      - name: Check outdated dependencies and create issue
        id: check-outdated-dependencies-and-create-issue
        uses: 1abhishekpandey/github-action-updated-dependencies-notifier@main
        with:
          outdated-dependency-names: "com.facebook.android:facebook-android-sdk"
          # outdated-dependency-names: "com.amplitude:android-sdk,
            # com.rudderstack.android.sdk:core,
            # com.clevertap.android:clevertap-android-sdk,
            # com.adobe.mobile:adobeMobileLibrary,
            # com.appboy:android-sdk-ui,
            # com.google.firebase:firebase-analytics,
            # com.moengage:moe-android-sdk,
            # com.appsflyer:af-android-sdk,
            # com.singular.sdk:singular_sdk,
            # com.fullstory:instrumentation-full,
            # com.kochava.base:tracker,
            # com.microsoft.appcenter:appcenter-analytics,
            # com.optimizely.ab:android-sdk,
            # com.bugsnag:bugsnag-android,
            # com.leanplum:leanplum-core,
            # io.intercom.android:intercom-sdk-base,
            # io.branch.sdk.android:library,
            # com.facebook.android:facebook-android-sdk,
            # com.adjust.sdk:adjust-android,
            # com.qualtrics:digital,
            # com.comscore:android-analytics
            # " 
          directory: "amplitude/build.gradle"
          # library: "amplitude"
          # repository-urls: "https://maven.fullstory.com"
          # repository-urls: "https://oss.sonatype.org/content/repositories/releases/, https://maven.google.com/, https://maven.singular.net/, https://maven.fullstory.com, https://s3-us-west-2.amazonaws.com/si-mobile-sdks/android/"
          # alternative-dependency-lookup: "com.singular.sdk:singular_sdk"
          # alternative-dependency-lookup-url: "https://maven.singular.net/com/singular/sdk/singular_sdk/maven-metadata.xml"
          
          title: "fix: update Facebook SDK to the latest version"
          assignee: "desusai7"
          labels: "outdatedDependency"
          color: "FBCA04"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the github issue url
        if: steps.check-outdated-dependencies-and-create-issue.outputs.issue-url != ''
        run: echo "The Github issue url is ${{ steps.check-outdated-dependencies-and-create-issue.outputs.issue-url }}"

      - name: Outdated dependency is detected
        if: steps.check-outdated-dependencies-and-create-issue.outputs.has-outdated-dependencies == 'true'
        run: echo "Outdated dependency is detected"